seedlink:
  server: "geofon.gfz-potsdam.de"
  streams:
    - network: "GE"
      station: "PSZ"
      channel: "BH?"
    - network: "GE"
      station: "MORC"
      channel: "BH?"
    - network: "GE"
      station: "STU"
      channel: "BH?"
    - network: "GE"
      station: "MATE"
      channel: "BH?"

influxdb:
  url: "http://localhost:8086"
  token: "my-secret-token"
  org: "my-org"
  bucket: "seismic_data"

logging:
  level: "INFO"
